name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-10"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzQyM2UyZTAtYzQ1MC00NzRkLWE3MTItZjJlYzYyNDUxMTYxIiwidGVuYW50X2lkIjoiNTlhZThlZDNjY2RkZDkzNWNjNWVlNWE1NmM0ZDY4Y2IxMzg5ZTAxM2I0MzQ1Y2Q3OTEyNjIwMWEzMTFjOTM0YiIsImludGVybmFsX3NlY3JldCI6ImQzNGM4NzcxLTNmM2YtNDk0Mi04NmU4LWJjNjVhM2E0NTNmMCJ9.H5W75EqZheuZruWNO8d-2GvQaIEe-T8v5U_a_Jm_0UY"

JWT_SECRET ="swati"